Repository Prashant-Bhapkar/Awesome-Security-Resources, pull requests merged in 2022-10, with the labels that each got.

#6 Update README.md
  Sub Domain Enumeration/README.md
Labels: enhancement

#7 Update README.md
  README.md
Labels: hactoberfest-accepted

#16 Addded two new email gathering tools
  Assets/havester.png
  Assets/knockmail.png
  Email Address/Discover Email Address/README.md
  README.md
Labels: hactoberfest-accepted

#12 Update README.md
  README.md
  Sub Domain Enumeration/README.md
Labels: good first issue, hactoberfest-accepted

#20 Add IDOR & LFI Attack to README.md - Hacktoberfest2022
  Attacks/README.md
  README.md
Labels: good first issue, hactoberfest-accepted

#22 CORS added in attacks
  Attacks/README.md
  README.md
Labels: good first issue, hactoberfest-accepted

#25 Updated network scanner and main readme
  Network Scanner/README.md
  README.md
Labels: good first issue

#31 added dir brute force tools
  Directory Bruteforce Tools/README.md
  README.md
Labels: hactoberfest-accepted

#30 Added IoT Intrusion Detection using Deep Learning
  Intrusion Detection System/iot-intrusion-detection.ipynb
  Intrusion Detection System/readme.md
Labels: good first issue, hactoberfest-accepted

#36 Automate subdomain Enumeration
  README.md
  Script/README.md
  Script/SubdomainScript/README.md
  Script/SubdomainScript/subdomain_enum.sh
  Sub Domain Enumeration/README.md
Labels: hactoberfest-accepted
